---
- name: Apply OS Configuration
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: play1

- name: Include a playbook from a collection
  ansible.builtin.import_playbook: os_mgmt.linux_config.os_config_update.yml

...

